"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-15 21:26:26.236316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.crypto  # EncryptedString column type (Fernet field encryption)


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('released_at', sa.Date(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions'))
    )
    op.create_index(op.f('ix_model_versions_model_type'), 'model_versions', ['model_type'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('org_type', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('operating_hours', sa.String(length=120), nullable=True),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('is_referral_partner', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('code', name=op.f('uq_organizations_code')),
    sa.UniqueConstraint('name', name=op.f('uq_organizations_name'))
    )
    op.create_table('pathway_configs',
    sa.Column('pathway_key', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('recommended_action', sa.String(length=200), nullable=False),
    sa.Column('referral_type', sa.String(length=40), nullable=True),
    sa.Column('timeframe_days', sa.Integer(), nullable=False),
    sa.Column('patient_message', sa.Text(), nullable=False),
    sa.Column('next_step_message', sa.Text(), nullable=False),
    sa.Column('required_service', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pathway_configs'))
    )
    op.create_index(op.f('ix_pathway_configs_pathway_key'), 'pathway_configs', ['pathway_key'], unique=False)
    op.create_table('barangays',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('eligible_population', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_barangays_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_barangays'))
    )
    op.create_index(op.f('ix_barangays_organization_id'), 'barangays', ['organization_id'], unique=False)
    op.create_table('inventory_batches',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('batch_number', sa.String(length=40), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('initial_quantity', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_inventory_batches_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_batches')),
    sa.UniqueConstraint('batch_number', name=op.f('uq_inventory_batches_batch_number'))
    )
    op.create_index(op.f('ix_inventory_batches_item_type'), 'inventory_batches', ['item_type'], unique=False)
    op.create_index(op.f('ix_inventory_batches_organization_id'), 'inventory_batches', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('full_name', app.core.crypto.EncryptedString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('cartridges',
    sa.Column('cartridge_code', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lot_expiry', sa.Date(), nullable=False),
    sa.Column('sim_profile', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], name=op.f('fk_cartridges_batch_id_inventory_batches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cartridges_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cartridges'))
    )
    op.create_index(op.f('ix_cartridges_cartridge_code'), 'cartridges', ['cartridge_code'], unique=True)
    op.create_index(op.f('ix_cartridges_organization_id'), 'cartridges', ['organization_id'], unique=False)
    op.create_table('health_workers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.String(length=80), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_health_workers_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_health_workers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_workers')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_health_workers_employee_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_health_workers_user_id'))
    )
    op.create_index(op.f('ix_health_workers_organization_id'), 'health_workers', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('patient_code', sa.String(length=32), nullable=False),
    sa.Column('birth_date', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('age_bracket', sa.String(length=16), nullable=False),
    sa.Column('phone', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('address', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('barangay_id', sa.Uuid(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('distance_category', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], name=op.f('fk_patient_profiles_barangay_id_barangays')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_patient_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_patient_profiles_user_id'))
    )
    op.create_index(op.f('ix_patient_profiles_barangay_id'), 'patient_profiles', ['barangay_id'], unique=False)
    op.create_index(op.f('ix_patient_profiles_patient_code'), 'patient_profiles', ['patient_code'], unique=True)
    op.create_table('program_aggregates',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('barangay_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('kits_distributed', sa.Integer(), nullable=False),
    sa.Column('samples_returned', sa.Integer(), nullable=False),
    sa.Column('valid_screenings', sa.Integer(), nullable=False),
    sa.Column('follow_up_required', sa.Integer(), nullable=False),
    sa.Column('follow_up_completed', sa.Integer(), nullable=False),
    sa.Column('total_days_to_follow_up', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], name=op.f('fk_program_aggregates_barangay_id_barangays')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_program_aggregates_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_aggregates'))
    )
    op.create_index(op.f('ix_program_aggregates_barangay_id'), 'program_aggregates', ['barangay_id'], unique=False)
    op.create_index(op.f('ix_program_aggregates_month'), 'program_aggregates', ['month'], unique=False)
    op.create_index(op.f('ix_program_aggregates_organization_id'), 'program_aggregates', ['organization_id'], unique=False)
    op.create_table('risk_rules',
    sa.Column('pathway_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_risk_rules_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_rules'))
    )
    op.create_index(op.f('ix_risk_rules_pathway_key'), 'risk_rules', ['pathway_key'], unique=False)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_label', sa.String(length=254), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('subject_patient_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['subject_patient_id'], ['patient_profiles.id'], name=op.f('fk_audit_logs_subject_patient_id_patient_profiles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_subject_patient_id'), 'audit_logs', ['subject_patient_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('consents',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('grantee_name', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_via', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_consents_organization_id_organizations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_consents_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_organization_id'), 'consents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_table('kits',
    sa.Column('kit_code', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('barangay_id', sa.Uuid(), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], name=op.f('fk_kits_barangay_id_barangays')),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], name=op.f('fk_kits_batch_id_inventory_batches')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_kits_organization_id_organizations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_kits_patient_id_patient_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kits'))
    )
    op.create_index(op.f('ix_kits_kit_code'), 'kits', ['kit_code'], unique=True)
    op.create_index(op.f('ix_kits_organization_id'), 'kits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_kits_patient_id'), 'kits', ['patient_id'], unique=False)
    op.create_table('readers',
    sa.Column('reader_code', sa.String(length=32), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('location_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('firmware_version', sa.String(length=20), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('last_calibration', sa.Date(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_cartridge_id', sa.Uuid(), nullable=True),
    sa.Column('total_analyses', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_cartridge_id'], ['cartridges.id'], name=op.f('fk_readers_current_cartridge_id_cartridges')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_readers_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readers')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_readers_serial_number'))
    )
    op.create_index(op.f('ix_readers_organization_id'), 'readers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_readers_reader_code'), 'readers', ['reader_code'], unique=True)
    op.create_table('screenings',
    sa.Column('screening_code', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('kit_id', sa.Uuid(), nullable=False),
    sa.Column('cartridge_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('reader_id', sa.Uuid(), nullable=True),
    sa.Column('barangay_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('analysis_stage', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('decision_trace', sa.JSON(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], name=op.f('fk_screenings_barangay_id_barangays')),
    sa.ForeignKeyConstraint(['cartridge_id'], ['cartridges.id'], name=op.f('fk_screenings_cartridge_id_cartridges')),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], name=op.f('fk_screenings_kit_id_kits')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_screenings_organization_id_organizations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_screenings_patient_id_patient_profiles')),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_screenings_reader_id_readers')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_screenings_reviewed_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screenings')),
    sa.UniqueConstraint('cartridge_id', name=op.f('uq_screenings_cartridge_id')),
    sa.UniqueConstraint('kit_id', name=op.f('uq_screenings_kit_id'))
    )
    op.create_index(op.f('ix_screenings_barangay_id'), 'screenings', ['barangay_id'], unique=False)
    op.create_index(op.f('ix_screenings_organization_id'), 'screenings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_screenings_outcome'), 'screenings', ['outcome'], unique=False)
    op.create_index(op.f('ix_screenings_patient_id'), 'screenings', ['patient_id'], unique=False)
    op.create_index(op.f('ix_screenings_reader_id'), 'screenings', ['reader_id'], unique=False)
    op.create_index(op.f('ix_screenings_released_at'), 'screenings', ['released_at'], unique=False)
    op.create_index(op.f('ix_screenings_screening_code'), 'screenings', ['screening_code'], unique=True)
    op.create_index(op.f('ix_screenings_status'), 'screenings', ['status'], unique=False)
    op.create_table('assay_results',
    sa.Column('screening_id', sa.Uuid(), nullable=False),
    sa.Column('reader_id', sa.Uuid(), nullable=True),
    sa.Column('control_valid', sa.Boolean(), nullable=False),
    sa.Column('hpv_signal', sa.String(length=20), nullable=False),
    sa.Column('hpv_genotype', sa.String(length=32), nullable=True),
    sa.Column('secondary_marker', sa.String(length=20), nullable=False),
    sa.Column('sample_quality', sa.String(length=20), nullable=False),
    sa.Column('assay_confidence', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=300), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reader_id'], ['readers.id'], name=op.f('fk_assay_results_reader_id_readers')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_assay_results_screening_id_screenings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assay_results')),
    sa.UniqueConstraint('screening_id', name=op.f('uq_assay_results_screening_id'))
    )
    op.create_table('care_pathways',
    sa.Column('screening_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('pathway_type', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recommended_action', sa.String(length=200), nullable=False),
    sa.Column('referral_type', sa.String(length=40), nullable=True),
    sa.Column('timeframe_days', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('recommended_facility_id', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_care_pathways_patient_id_patient_profiles')),
    sa.ForeignKeyConstraint(['recommended_facility_id'], ['organizations.id'], name=op.f('fk_care_pathways_recommended_facility_id_organizations')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_care_pathways_screening_id_screenings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_pathways')),
    sa.UniqueConstraint('screening_id', name=op.f('uq_care_pathways_screening_id'))
    )
    op.create_index(op.f('ix_care_pathways_patient_id'), 'care_pathways', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_pathways_status'), 'care_pathways', ['status'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('assay_result_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('analysis_type', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=False),
    sa.Column('signal_intensity', sa.JSON(), nullable=False),
    sa.Column('control_validity', sa.Boolean(), nullable=False),
    sa.Column('prediction', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('pipeline', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assay_result_id'], ['assay_results.id'], name=op.f('fk_ai_analyses_assay_result_id_assay_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_ai_analyses_model_version_id_model_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index(op.f('ix_ai_analyses_assay_result_id'), 'ai_analyses', ['assay_result_id'], unique=False)
    op.create_table('referrals',
    sa.Column('referral_code', sa.String(length=32), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('screening_id', sa.Uuid(), nullable=False),
    sa.Column('care_pathway_id', sa.Uuid(), nullable=False),
    sa.Column('source_org_id', sa.Uuid(), nullable=False),
    sa.Column('destination_org_id', sa.Uuid(), nullable=False),
    sa.Column('referral_type', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preferred_schedule', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clinical_notes', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['care_pathway_id'], ['care_pathways.id'], name=op.f('fk_referrals_care_pathway_id_care_pathways')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_referrals_created_by_id_users')),
    sa.ForeignKeyConstraint(['destination_org_id'], ['organizations.id'], name=op.f('fk_referrals_destination_org_id_organizations')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_referrals_patient_id_patient_profiles')),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_referrals_screening_id_screenings')),
    sa.ForeignKeyConstraint(['source_org_id'], ['organizations.id'], name=op.f('fk_referrals_source_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals'))
    )
    op.create_index(op.f('ix_referrals_care_pathway_id'), 'referrals', ['care_pathway_id'], unique=False)
    op.create_index(op.f('ix_referrals_destination_org_id'), 'referrals', ['destination_org_id'], unique=False)
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=True)
    op.create_index(op.f('ix_referrals_screening_id'), 'referrals', ['screening_id'], unique=False)
    op.create_index(op.f('ix_referrals_source_org_id'), 'referrals', ['source_org_id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('appointments',
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_appointments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_appointments_recorded_by_id_users')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_appointments_referral_id_referrals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index(op.f('ix_appointments_referral_id'), 'appointments', ['referral_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('referral_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', app.core.crypto.EncryptedString(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_follow_ups_recorded_by_id_users')),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_follow_ups_referral_id_referrals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follow_ups'))
    )
    op.create_index(op.f('ix_follow_ups_referral_id'), 'follow_ups', ['referral_id'], unique=False)
    op.create_table('passport_events',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('institution_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('screening_id', sa.Uuid(), nullable=True),
    sa.Column('referral_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('fk_passport_events_patient_id_patient_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_passport_events_referral_id_referrals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], name=op.f('fk_passport_events_screening_id_screenings'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passport_events'))
    )
    op.create_index(op.f('ix_passport_events_patient_id'), 'passport_events', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passport_events_patient_id'), table_name='passport_events')
    op.drop_table('passport_events')
    op.drop_index(op.f('ix_follow_ups_referral_id'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_appointments_referral_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_source_org_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_screening_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_destination_org_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_care_pathway_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_ai_analyses_assay_result_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_care_pathways_status'), table_name='care_pathways')
    op.drop_index(op.f('ix_care_pathways_patient_id'), table_name='care_pathways')
    op.drop_table('care_pathways')
    op.drop_table('assay_results')
    op.drop_index(op.f('ix_screenings_status'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_screening_code'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_released_at'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_reader_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_patient_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_outcome'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_organization_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_barangay_id'), table_name='screenings')
    op.drop_table('screenings')
    op.drop_index(op.f('ix_readers_reader_code'), table_name='readers')
    op.drop_index(op.f('ix_readers_organization_id'), table_name='readers')
    op.drop_table('readers')
    op.drop_index(op.f('ix_kits_patient_id'), table_name='kits')
    op.drop_index(op.f('ix_kits_organization_id'), table_name='kits')
    op.drop_index(op.f('ix_kits_kit_code'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_organization_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_subject_patient_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_risk_rules_pathway_key'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_program_aggregates_organization_id'), table_name='program_aggregates')
    op.drop_index(op.f('ix_program_aggregates_month'), table_name='program_aggregates')
    op.drop_index(op.f('ix_program_aggregates_barangay_id'), table_name='program_aggregates')
    op.drop_table('program_aggregates')
    op.drop_index(op.f('ix_patient_profiles_patient_code'), table_name='patient_profiles')
    op.drop_index(op.f('ix_patient_profiles_barangay_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_health_workers_organization_id'), table_name='health_workers')
    op.drop_table('health_workers')
    op.drop_index(op.f('ix_cartridges_organization_id'), table_name='cartridges')
    op.drop_index(op.f('ix_cartridges_cartridge_code'), table_name='cartridges')
    op.drop_table('cartridges')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_inventory_batches_organization_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_item_type'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_index(op.f('ix_barangays_organization_id'), table_name='barangays')
    op.drop_table('barangays')
    op.drop_index(op.f('ix_pathway_configs_pathway_key'), table_name='pathway_configs')
    op.drop_table('pathway_configs')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_model_versions_model_type'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
